#!/bin/sh

# TODO: I really, really should learn Perl.

awk '
BEGIN {
    printf "This is it folks, over the top\n"
    for (n=0 ; n<1030 ; n+=5)
    {
    	printf "%04d|", n+4
    }
    printf "\n"
    exit
}' < /dev/null
