#!/bin/sh

FORCE=no
CVSTAG=
BUILDHOST=
LOCALHOST=$(uname -n|cut -d. -f1)
RPMDEST=
COPYTARBALL=no
# This file is both controlled and also emitted as part of the build,
# which is probably a bad idea, but regardless it needs to be ignored
# when checking for modified files.
CVSIGNORES="aclocal.m4"

fatal ()
{
    echo "ERROR: $*" >&2
    exit 1
}

usage ()
{
    echo "Usage: $0 [--force] [--cvs-update] [--build-host=host] [--rpm-destination=[host:]dir]"
    exit 1
}

boolopt ()
{
    case "${2#*=}" in
    yes) eval $1=yes ;;
    no) eval $1=no ;;
    *) fatal "Bad boolean option \"$2\"" ;;
    esac
}

while [ $# -gt 0 ]; do
    case "$1" in
    --force|-f) boolopt FORCE yes ;;
    --force=*) boolopt FORCE $1 ;;
    -h|--build-host) BUILDHOST=$2 ; shift ;;
    --build-host=*) BUILDHOST=${1#*=} ;;
    -u|--cvs-update) CVSTAG=HEAD ;;
    --cvs-update=*) CVSTAG=${1#*=} ;;
    -d|--rpm-destination) RPMDEST=$2 ; shift ;;
    --rpm-destination=*) RPMDEST=${1#*=} ;;
    -t|--copy-tarball) boolopt COPYTARBALL yes ; shift ;;
    --copy-tarball=*) boolopt COPYTARBALL $1 ;;
    *) usage ;;
    esac
    shift
done

# echo FORCE=$FORCE
# echo BUILDHOST=$BUILDHOST
# echo CVSTAG=$CVSTAG
# echo RPMDEST=$RPMDEST
# exit

case "$BUILDHOST" in
""|"$LOCALHOST"|localhost)
    echo "Building on local host ($LOCALHOST)"
    if [ -z "$__BUILDRPM_LOGGED" ]; then
	export __BUILDRPM_LOGGED=yes
	exec ./buildrpm \
	    	--cvs-update=$CVSTAG \
		--force=$FORCE \
		--rpm-destination=$RPMDEST \
		--copy-tarball=$COPYTARBALL \
		 2>&1 | tee build.$LOCALHOST.log
    fi
    ;;
*)
    echo "Building on remote host \"$BUILDHOST\""
    (
	set -x
	ssh $BUILDHOST "cd $PWD && \
    	    ./buildrpm \
	    	--cvs-update=$CVSTAG \
		--force=$FORCE \
		--rpm-destination=${RPMDEST:-$LOCALHOST:$PWD} \
		--copy-tarball=$COPYTARBALL"
    ) 2>&1 | tee build.$BUILDHOST.log
    exit
    ;;
esac

set -- `sed -n -e 's|^AM_INIT_AUTOMAKE(\([^,]\+\),\([^)]\+\))|\1 \2|p' < configure.in` notfound
if [ "$1" = notfound ]; then
    AUTOMAKE=no
    eval `egrep '^(PACKAGE|VERSION)=' < configure.in`
else
    AUTOMAKE=yes
    PACKAGE=$1
    VERSION=$2
fi

SPECFILE=${PACKAGE}.spec
RPMDIR=rpm.d

TARBALL=`awk '/^Source:/{print $2}' < $SPECFILE.in`
case "$TARBALL" in
*.tar.gz) TARBALL=${PACKAGE}-${VERSION}.tar.gz ;;
*.tgz) TARBALL=${PACKAGE}-${VERSION}.tgz ;;
*.tar.bz2) TARBALL=${PACKAGE}-${VERSION}.tar.bz2 ;;
*) fatal "cannot calculate tarball extension from $SPECFILE" ;;
esac

if [ -x /usr/bin/rpmbuild ] ; then
    RPMBUILD=rpmbuild
else
    RPMBUILD=rpm
fi

# Calculate a string which identifies the Linux distro
DISTRO=
if [ -f /etc/redhat-release ]; then
    DISTRO=rh$(sed -e 's|.*release[ \t]\+\([^ \t]\+\).*|\1|g' < /etc/redhat-release)
fi

#echo PACKAGE=$PACKAGE
#echo VERSION=$VERSION
#echo TARBALL=$TARBALL
#echo RPMDIR=$RPMDIR
#echo DISTRO=$DISTRO
#echo RPMBUILD=$RPMBUILD
#echo CVSIGNORES=\"$CVSIGNORES\"
#echo FORCE=$FORCE
#exit 1

case "$CVSTAG" in
"")
    # Do nothing
    ;;
HEAD)
    echo "Checking for locally changed files"

    CVSIGNORES_RE=$(echo $CVSIGNORES | sed -e 's/^[ \t]*/^(/g'  -e 's/[ \t]*$/)$/g' -e 's/[ \t][ \t]*/|/g')

    CHANGED=$(cvs -nq up | awk '$1~/^[MC]$/ && $2!~/'$CVSIGNORES_RE'/{print $2}')
    [ -z "$CHANGED" ] || \
    	fatal "These files are changed in this work area: $CHANGED"
    echo "Updating files from CVS"
    (
    	set -x
    	cvs -q up || exit 1
    ) || exit 1
    ;;
*)
    echo "Checking out a new directory with tag $CVSTAG"

    BUILDDIR=build.d
    [ -d $BUILDDIR ] && rm -rf $BUILDDIR
    ROOT=$(cat CVS/Root)
    REPOS=$(cat CVS/Repository)

    echo "Updating files from CVS"
    (
    	set -x
	cvs -d $ROOT co -r$CVSTAG -d $BUILDDIR $REPOS || exit 1
    ) || fatal "Can't check out from CVS"
    [ -z "$RPMDEST" ] && RPMDEST=$(/bin/pwd)
    cd $BUILDDIR || fatal "Checkout succeeded but no directory"
    ;;
esac

if [ $FORCE = yes ]; then
    echo "Removing files to force rebuild"
    (
    	set -x
	/bin/rm -rf config.status config.cache autom4te.cache
	/bin/rm -f $SPECFILE $TARBALL
    )
fi

if [ ! -f $SPECFILE ]; then
    echo "Specfile missing, building"
    (
    	set -x
	aclocal
	autoconf
	autoheader
	test "$AUTOMAKE" = yes && automake -a
	./configure
    )
    [ -f $SPECFILE ] || fatal "Can't build $SPECFILE, giving up"
fi

if [ ! -f $TARBALL ]; then
    echo "Tarball missing, building"
    (
    	set -x
	make dist
    )
    [ -f $TARBALL ] || fatal "Can't build $TARBALL, giving up"
fi

echo "Building $RPMDIR directory tree"
/bin/rm -rf $RPMDIR
mkdir -p $RPMDIR
(cd $RPMDIR ; mkdir -p BUILD RPMS/i386 RPMS/`uname -m` SPECS SRPMS )

echo "Building RPMs"
(
    set -x
    $RPMBUILD -bb \
	--define "_topdir $PWD/$RPMDIR" \
	--define "_sourcedir $PWD" \
	--verbose \
	$SPECFILE || exit 1
)

copyfile ()
{
    local from=$1
    local to=$1

    case "$RPMDEST" in
    "")
	echo "Moving $from -> $to"
	mv $from $f2 || exit 1
    	;;
    *:*)
	echo "Copying $from -> $RPMDEST/$to"
	scp $from $RPMDEST/$to || exit 1
    	;;
    *)
	echo "Moving $from -> $RPMDEST/$to"
	mv $from $RPMDEST/$to || exit 1
    	;;
    esac
}

if [ $COPYTARBALL = yes -a ! -z "$RPMDEST" ] ; then
    echo "Copying tarball to destination"
    copyfile $TARBALL $TARBALL
fi

echo "Copying RPMs to destination"
for f in $(find $RPMDIR/RPMS -type f -name \*.rpm) ; do
    f2=$(echo $(basename $f) | sed -e 's|^\([a-z-]\+-\)|\1'${DISTRO}${DISTRO:+-}'|')
    copyfile $f $f2
done

