#!/usr/bin/awk -f
#
# $Id: changes2html,v 1.1 1999-10-09 15:22:01 gnb Exp $
#
# Awk script to convert the change log into HTML for the Web page
#
BEGIN {
    listlevel=0
    parcount=0
}
function set_list_level(lev)
{
    while (listlevel < lev)
    {
    	print "<UL>"
    	listlevel++;
    }
    while (listlevel > lev)
    {
    	print "</UL>"
    	listlevel--;
    }
    listlevel = lev
}
/^\* / {
    set_list_level(0)
    print "<H2>"substr($0,2,length($0))"</H2>"
    next
}
/^x  / {
    set_list_level(1)
    print "<LI>"substr($0,4,length($0))
    next
}
#/^$/ {
#    set_list_level(0)
#    if (parcount > 0) print "</P>"
#    print "<P>"
#    parcount++;
#    next;
#}
{
    print $0
}
END {
    set_list_level(0)
}
