
TOPDIR=	../../..
include $(TOPDIR)/crud.mk

SUBDIRS=	level5a level5b level5c
include $(TOPDIR)/recurse.mk

.PHONY: this_directory_is_test_level2_level3_level4a
this_directory_is_test_level2_level3_level4a:
